### PR TITLE
347 keyboard hiding text fields

### PR DESCRIPTION
**Pull request by zlatna**
- Add/integrate 'IQKeyboardManager' pod
- Update the .gitignore

### CODE REVIEW

**Review by andredublin — APPROVED** [review]
lgtm

**Comment by BurningAXE** [comment]
Hm, the .xcworkspace file is completely empty in this branch!?

**Comment by zlatna** [comment]
.xcworkspace gets generated after pod install, If the pods are not modified we don't need to keep it.

**Comment by BurningAXE** [comment]
That's better! When we complete all tasks for the pending release and delete all feature branches, we might ignore the workspace then and start clean.
As for the fix itself - this lib is wonderful. Did check on iPhone SE and XS simulators and looks OK. The only thing I noticed is this:
simulator screen shot - iphone xs - 2018-12-17 at 09 25 19
There is a gap between the comment entry field and the keyboard on iPhoneXS (probably on all roundy iPhones). This is due to some manual fix before the lib was added.
Steps for reproducing:
- Add a signal (first switch to test environment by tapping 7 times on the title in the main screen)
- Open the signal
- Tap the comment entry fields to bring the keyboard

**Pull request closed without merging**
